### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by babinc** [nasso/screensnap#1]
Hello, 

I'm happy to see the rust screensnap program, unfortunately I don't think it is working on my windows 10 system.

My steps:
1. cloned the repo
2. Checked out version 1.0.0
3. Built the release version
4. Ran the build

When I press "print screen" the screen darkens a little. I'm not sure if this is screensnap or the default windows operations. I have always used another program for screenshot, so I'm not even sure what windows does by default. After the screen darkens a little I select an area but nothing happens after that. 

Thanks,
Carman

**Comment by nasso** [comment]
It actually isn't supposed to do anything more than copying the area you've selected to your clipboard!
Try pasting it somewhere like Paint, and you should have your screenshot there (hopefully).

Let me know if it isn't working!

**Comment by nasso** [comment]
Closing this as no more information has been given by the OP.
